[project]
name = "ai-lab-challenge-kpmg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "googlesearch-python>=1.3.0",
]
